### ISSUE TITLE
Sublime Text 3 

### ISSUE THREAD

**Issue by BorisRaymondPerier** [roesti77/Sublime-Open-Shading-Language#1]
Hey, 
Sublime-Open-Shading-Language seem to not be available in the sublime text 3 package controler yet.

**Comment by roesti77** [comment]
I updated the Package today. Use Branch SublimeText3. In the bin Folder there is a Packagefile to Download. Package Controll will come later.

**Comment by BorisRaymondPerier** [comment]
Sorry I haven't see that. Thanks for your quick reply. Thanks for the package
