### ISSUE TITLE
Direct Connection to Osl Node ?

### ISSUE THREAD

**Issue by SheepDomination** [roesti77/Sublime-Open-Shading-Language#2]
Hi, is it possible to connect from sublime to PXROsl for Maya ? What is [meant](https://blenderartists.org/forum/showthread.php?292858-Sublime-Open-Shading-Language-Plugin) by; Also you can Testbuild your Shader ?

**Comment by roesti77** [comment]
Hi,
in Blender you needed to load the source File and then build the shader in Blender. In Sublime you can build the shader with oslc (That's what I meant with Testbuild). With a quick look, I have read that PXROsl needs precompiled oso files. So you can build them out of Sublime and load it into PXROsl.

**Comment by SheepDomination** [comment]
Can your extension pre-compile OSO files for use in PXROSL ? Sorry if you answer this question in your previous reply, I didn't understand ?

OSLC & OSO files are completely different or one in the same ?

**Comment by roesti77** [comment]
Oslc is the openshadinglanguage compiler. It takes a text file with the shader and creates a binary (oso open shading object) from it. this oso Files can then be loaded in pxrosl ( as far as i read).

**Comment by SheepDomination** [comment]
Can you compile the extension for Visual Studio Code ?

**Comment by roesti77** [comment]
No. This is a Sublime Text Plugin, using the Sublime Text API.
